import { Client } from './types';

export const MOCK_CLIENTS: Client[] = [
  {
    id: 1,
    name: 'Sarah Johnson',
    status: 'active',
    condition: 'Anxiety',
    email: 'sarah.j@email.com',
    phone: '(888) 123-4567',
    totalSessions: 12,
    lastSession: '2024-10-08',
    nextSession: '2024-10-09 09:00 AM',
    treatmentTags: ['Generalized Anxiety Disorder', 'Panic Attacks', 'Work-related Stress'],
    crisisHistory: [
      {
        id: 101,
        date: '2024-09-24',
        title: 'Severe panic attack during work presentation',
        severity: 'high',
        actionsTaken: 'Immediate grounding techniques provided. Client successfully used 5-4-3-2-1 sensory method to calm down. Created emergency action plan for future episodes.',
        tags: ['Immediate Action', 'Grounding', 'Safety Plan'],
      },
      {
        id: 102,
        date: '2024-08-15',
        title: 'Elevated anxiety with intrusive thoughts',
        severity: 'medium',
        actionsTaken: 'Cognitive restructuring exercises. Discussed thought-stopping techniques. Increased session frequency temporarily.',
        tags: ['CBT', 'Coping Skills'],
      },
    ],
    progressItems: [
      { label: 'Reduce anxiety symptoms', value: 66 },
      { label: 'Improve coping mechanisms', value: 80 },
      { label: 'Better sleep patterns', value: 45 },
    ],
    sessionHistory: [
      { id: 201, date: '2024-10-08 09:30 AM', type: 'Therapy Session', summary: 'Significant improvement in managing anxiety triggers.', details: 'Client showed significant improvement in managing anxiety triggers. Discussed workplace stressors and developed specific coping strategies for mornings. Client reported using breathing techniques successfully 3 times this week. However, still practice progressive muscle relaxation before bed.' },
      { id: 202, date: '2024-09-29 09:30 AM', type: 'Therapy Session', summary: 'Introduced new breathing techniques', details: 'Focused on relaxation techniques and distress tolerance skills.' },
      { id: 203, date: '2024-09-25 08:00 AM', type: 'Crisis Intervention', summary: 'Crisis intervention - panic attack at work' },
      { id: 204, date: '2024-09-18 09:30 AM', type: 'Follow-up Session', summary: 'Reviewed homework assignments' },
      { id: 205, date: '2024-09-08 09:30 AM', type: 'Initial Assessment', summary: 'Comprehensive intake assessment' },
    ],
  },
  {
    id: 2,
    name: 'Michael Smith',
    status: 'active',
    condition: 'Depression',
    email: 'michael.s@email.com',
    phone: '(888) 987-6543',
    totalSessions: 20,
    lastSession: '2024-10-05',
    nextSession: '2024-10-10 11:00 AM',
    treatmentTags: ['CBT', 'Mood Tracking'],
    crisisHistory: [],
    progressItems: [{ label: 'Increase energy levels', value: 40 }],
    sessionHistory: [],
  },
  {
    id: 3,
    name: 'Emily Davis',
    status: 'inactive',
    condition: 'PTSD',
    email: 'emily.d@email.com',
    phone: '(888) 555-1234',
    totalSessions: 8,
    lastSession: '2024-09-20',
    nextSession: 'N/A',
    treatmentTags: ['Trauma-Focused CBT'],
    crisisHistory: [],
    progressItems: [],
    sessionHistory: [],
  },
  {
    id: 4,
    name: 'David Brown',
    status: 'active',
    condition: 'Bipolar Disorder',
    email: 'david.b@email.com',
    phone: '(888) 111-2222',
    totalSessions: 15,
    lastSession: '2024-10-03',
    nextSession: '2024-10-12 02:00 PM',
    treatmentTags: ['Medication Management', 'Psychoeducation'],
    crisisHistory: [],
    progressItems: [],
    sessionHistory: [],
  },
  {
    id: 5,
    name: 'Laura Wilson',
    status: 'active',
    condition: 'Relationship Issues',
    email: 'laura.w@email.com',
    phone: '(888) 333-4444',
    totalSessions: 10,
    lastSession: '2024-10-01',
    nextSession: '2024-10-11 03:30 PM',
    treatmentTags: ['Couples Therapy', 'Communication Skills'],
    crisisHistory: [],
    progressItems: [],
    sessionHistory: [],
  },
];
